from datetime import datetime, timedelta, timezone
from typing import Union, Annotated

from contextlib import asynccontextmanager

import jwt
from jwt.exceptions import InvalidTokenError
from fastapi import Depends, FastAPI, HTTPException, status, Query
from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm
from fastapi.middleware.cors import CORSMiddleware

from pwdlib import PasswordHash

from pydantic_settings import BaseSettings, SettingsConfigDict

import os
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

from pydantic import BaseModel

from app.db import SessionDep, create_db_and_tables
from app.auth import User, OAuth2SchemeDI, CurrentActiveUserDI, router as auth_router


from app.routers.hero import router as hero_router
from app.routers.metric_value import router as metric_value_router
from app.routers.metric import router as metric_router
from app.routers.module import router as module_router
from app.routers.question_response import router as question_response_router
from app.routers.question import router as question_router
from app.routers.session import router as session_router
from app.routers.text_feedback import router as text_feedback_router

from sqlmodel import Field, Session, SQLModel, create_engine, select

SECRET_KEY = "02b68540063b967e41f15dced7b908d3a4e69fc6a7ac8ff658b4f73e1d55582a"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

@asynccontextmanager
async def lifespan(app: FastAPI):
    create_db_and_tables()
    yield

db_uri = os.environ.get("MONGODB_URI")



db_success = ""

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="token")


app = FastAPI(lifespan=lifespan)

app.include_router(auth_router) # prefix: what comes before the request when doing an HTTP request (e.g. "/auth/token")
app.include_router(hero_router) # token: just for easier API documentation

app.include_router(metric_value_router)
app.include_router(metric_router)
app.include_router(module_router)
app.include_router(question_response_router)
app.include_router(question_router)
app.include_router(session_router)
app.include_router(text_feedback_router)


# validated hero now also has an id generated by the database
# the actual return type is Hero but response model is HeroPublic so fastapi validates, serielizes data


origins = [
    "https://swipeback.pages.dev",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/users/me/", response_model=User)
async def read_users_me(current_user: CurrentActiveUserDI):
    return current_user
@app.get("/user/me/items")
async def read_own_items(
    current_user: CurrentActiveUserDI
):
    return [{"item_id": "Foo", "owner": current_user.username}]




@app.get("/")
def read_root():
    return {"Hello": "World", "db_success": db_success}



@app.get("/items/{item_id}")
def read_item(item_id: int, q: Union[str, None] = None):
    return {"item_id": item_id, "q": q}

@app.get("/items")
async def read_items(token: OAuth2SchemeDI):
    return {"token": token}
